name: Otus Workflow
on:
  workflow_dispatch:

jobs:
  test_webserver:
    runs-on: ubuntu-latest
    container: gradle:latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run tests
      run: gradle test
    - uses: actions/upload-artifact@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        name: mytest
        path: '**/build/test-results/test/*.xml'
    - uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/*.xml'
    
