name: Otus Workflow
on:
  workflow_dispatch:

jobs:
  test_webserver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build Project
      run: gradle build
    - name: Run tests
      run: gradle test
