name: Otus Workflow
on:
  workflow_dispatch:

jobs:
  test_webserver:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run tests
      run: gradle test
    - uses: actions/upload-artifact@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        name: mytest
        path: '**/build/test-results/test/*.xml'
    - uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/*.xml'
    
